name: Deploy Edge App v2
description: |
  Manually deploy any edge app to either the staging (QC) or production environment.
  Always uses the latest master branch.

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (stage or production)'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - production

      edge_app_name:
        description: 'Folder name of the edge app (under edge-apps/)'
        required: true
        default: ''

# üè∑Ô∏è This will be shown in the Actions run list and run page title
run-name: Deploying ${{ inputs.edge_app_name }} to ${{ inputs.environment }} by @${{ github.actor }}

jobs:
  deploy-stage:
    if: ${{ inputs.environment == 'stage' }}
    name: Deploying ${{ inputs.edge_app_name }} - Stage (QC)
    runs-on: ubuntu-latest
    env:
      APP_PATH: edge-apps/${{ inputs.edge_app_name }}
      MANIFEST_FILE_NAME: screenly_qc.yml
      SCREENLY_API_TOKEN: ${{ secrets.SCREENLY_API_TOKEN_AUTOMATED_QC }}

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Deploy Edge App to Stage
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ env.SCREENLY_API_TOKEN }}
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }} --manifest-file=${{ env.APP_PATH }}/${{ env.MANIFEST_FILE_NAME }}

  deploy-production:
    if: ${{ inputs.environment == 'production' }}
    name: Deploying ${{ inputs.edge_app_name }} - Production
    runs-on: ubuntu-latest
    env:
      APP_PATH: edge-apps/${{ inputs.edge_app_name }}
      MANIFEST_FILE_NAME: screenly.yml
      SCREENLY_API_TOKEN: ${{ secrets.SCREENLY_API_TOKEN }}

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Deploy Edge App to Production
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ env.SCREENLY_API_TOKEN }}
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }} --manifest-file=${{ env.APP_PATH }}/${{ env.MANIFEST_FILE_NAME }}
